services:
  go:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
  
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: